# docs: <https://golangci-lint.run/usage/configuration/>
run:
  skip-dirs:
    - ".*/.asdf/.*"

  build-tags:
    - integration

linters:
  enable:
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gci
    - gosec
    - misspell
    - tagalign
    - wsl

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
