// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AutoLoginState is an autogenerated mock type for the AutoLoginState type
type AutoLoginState struct {
	mock.Mock
}

type AutoLoginState_Expecter struct {
	mock *mock.Mock
}

func (_m *AutoLoginState) EXPECT() *AutoLoginState_Expecter {
	return &AutoLoginState_Expecter{mock: &_m.Mock}
}

// AutoLogin provides a mock function with given fields:
func (_m *AutoLoginState) AutoLogin() (bool, error) {
	ret := _m.Called()

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoLoginState_AutoLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoLogin'
type AutoLoginState_AutoLogin_Call struct {
	*mock.Call
}

// AutoLogin is a helper method to define mock.On call
func (_e *AutoLoginState_Expecter) AutoLogin() *AutoLoginState_AutoLogin_Call {
	return &AutoLoginState_AutoLogin_Call{Call: _e.mock.On("AutoLogin")}
}

func (_c *AutoLoginState_AutoLogin_Call) Run(run func()) *AutoLoginState_AutoLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AutoLoginState_AutoLogin_Call) Return(_a0 bool, _a1 error) *AutoLoginState_AutoLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AutoLoginState_AutoLogin_Call) RunAndReturn(run func() (bool, error)) *AutoLoginState_AutoLogin_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoLogin provides a mock function with given fields: _a0
func (_m *AutoLoginState) SetAutoLogin(_a0 bool) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AutoLoginState_SetAutoLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoLogin'
type AutoLoginState_SetAutoLogin_Call struct {
	*mock.Call
}

// SetAutoLogin is a helper method to define mock.On call
//   - _a0 bool
func (_e *AutoLoginState_Expecter) SetAutoLogin(_a0 interface{}) *AutoLoginState_SetAutoLogin_Call {
	return &AutoLoginState_SetAutoLogin_Call{Call: _e.mock.On("SetAutoLogin", _a0)}
}

func (_c *AutoLoginState_SetAutoLogin_Call) Run(run func(_a0 bool)) *AutoLoginState_SetAutoLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *AutoLoginState_SetAutoLogin_Call) Return(_a0 error) *AutoLoginState_SetAutoLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AutoLoginState_SetAutoLogin_Call) RunAndReturn(run func(bool) error) *AutoLoginState_SetAutoLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewAutoLoginState creates a new instance of AutoLoginState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoLoginState(t interface {
	mock.TestingT
	Cleanup(func())
}) *AutoLoginState {
	mock := &AutoLoginState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
