// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	state "github.com/nobbs/uptime-kuma-api/pkg/state"
	mock "github.com/stretchr/testify/mock"
)

// ImportantHeartbeatListState is an autogenerated mock type for the ImportantHeartbeatListState type
type ImportantHeartbeatListState struct {
	mock.Mock
}

type ImportantHeartbeatListState_Expecter struct {
	mock *mock.Mock
}

func (_m *ImportantHeartbeatListState) EXPECT() *ImportantHeartbeatListState_Expecter {
	return &ImportantHeartbeatListState_Expecter{mock: &_m.Mock}
}

// ImportantHeartbeats provides a mock function with given fields: monitorId
func (_m *ImportantHeartbeatListState) ImportantHeartbeats(monitorId int) ([]state.Heartbeat, error) {
	ret := _m.Called(monitorId)

	var r0 []state.Heartbeat
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]state.Heartbeat, error)); ok {
		return rf(monitorId)
	}
	if rf, ok := ret.Get(0).(func(int) []state.Heartbeat); ok {
		r0 = rf(monitorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.Heartbeat)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(monitorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportantHeartbeatListState_ImportantHeartbeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportantHeartbeats'
type ImportantHeartbeatListState_ImportantHeartbeats_Call struct {
	*mock.Call
}

// ImportantHeartbeats is a helper method to define mock.On call
//   - monitorId int
func (_e *ImportantHeartbeatListState_Expecter) ImportantHeartbeats(monitorId interface{}) *ImportantHeartbeatListState_ImportantHeartbeats_Call {
	return &ImportantHeartbeatListState_ImportantHeartbeats_Call{Call: _e.mock.On("ImportantHeartbeats", monitorId)}
}

func (_c *ImportantHeartbeatListState_ImportantHeartbeats_Call) Run(run func(monitorId int)) *ImportantHeartbeatListState_ImportantHeartbeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ImportantHeartbeatListState_ImportantHeartbeats_Call) Return(beats []state.Heartbeat, err error) *ImportantHeartbeatListState_ImportantHeartbeats_Call {
	_c.Call.Return(beats, err)
	return _c
}

func (_c *ImportantHeartbeatListState_ImportantHeartbeats_Call) RunAndReturn(run func(int) ([]state.Heartbeat, error)) *ImportantHeartbeatListState_ImportantHeartbeats_Call {
	_c.Call.Return(run)
	return _c
}

// SetImportantHeartbeats provides a mock function with given fields: monitorId, beats, overwrite
func (_m *ImportantHeartbeatListState) SetImportantHeartbeats(monitorId int, beats []state.Heartbeat, overwrite bool) error {
	ret := _m.Called(monitorId, beats, overwrite)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []state.Heartbeat, bool) error); ok {
		r0 = rf(monitorId, beats, overwrite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ImportantHeartbeatListState_SetImportantHeartbeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetImportantHeartbeats'
type ImportantHeartbeatListState_SetImportantHeartbeats_Call struct {
	*mock.Call
}

// SetImportantHeartbeats is a helper method to define mock.On call
//   - monitorId int
//   - beats []state.Heartbeat
//   - overwrite bool
func (_e *ImportantHeartbeatListState_Expecter) SetImportantHeartbeats(monitorId interface{}, beats interface{}, overwrite interface{}) *ImportantHeartbeatListState_SetImportantHeartbeats_Call {
	return &ImportantHeartbeatListState_SetImportantHeartbeats_Call{Call: _e.mock.On("SetImportantHeartbeats", monitorId, beats, overwrite)}
}

func (_c *ImportantHeartbeatListState_SetImportantHeartbeats_Call) Run(run func(monitorId int, beats []state.Heartbeat, overwrite bool)) *ImportantHeartbeatListState_SetImportantHeartbeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]state.Heartbeat), args[2].(bool))
	})
	return _c
}

func (_c *ImportantHeartbeatListState_SetImportantHeartbeats_Call) Return(err error) *ImportantHeartbeatListState_SetImportantHeartbeats_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ImportantHeartbeatListState_SetImportantHeartbeats_Call) RunAndReturn(run func(int, []state.Heartbeat, bool) error) *ImportantHeartbeatListState_SetImportantHeartbeats_Call {
	_c.Call.Return(run)
	return _c
}

// NewImportantHeartbeatListState creates a new instance of ImportantHeartbeatListState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImportantHeartbeatListState(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImportantHeartbeatListState {
	mock := &ImportantHeartbeatListState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
